field.storage.node.field_content_visibility:
  expected_config: { }
  update_actions:
    change:
      settings:
        allowed_values:
          -1:
            label: 'Public'
          0:
            label: 'Community'
          1:
            label: 'Group members'
