name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs:
    name: PHPCS
    # Need to define php version as per https://github.com/actions/virtual-environments/issues/1816
    # ubuntu-latest uses php 8.0 by default so checks will fail.
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/composer@v4
        with:
          php_version: '7.4'
          composer_version: '2'
      # Install composer dependencies so we have drupal/coder which adds our codesniffer, the bin/phpcs file
      # and dealerdirect/phpcodesniffer-composer-installer which changes the installer_path configuring all sniffs.
      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
